server:
  base_url: "https://my-final-search.onrender.com"  # <-- ЗАМЕНИТЕ ЭТОТ URL НА ВАШ РЕАЛЬНЫЙ URL С RENDER
  use_forwarded_host: true

search:
  language: "ru-RU"

bot_detection:
  enabled: false

engines:
  - name: google
    engine: google
    shortcut: g
    
  - name: bing
    engine: bing
    shortcut: b

  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
